baseURL = 'https://xhp0.gitee.io/xsdb/'
languageCode = 'zh-cn'
title = '个人资料库'
theme = 'mini'
defaultContentLanguage = 'zh'
paginate = 15
relativeurls = true


[permalinks]
  posts = "/:slug/"
  
[markup.goldmark.renderer]
  unsafe = true

[params]
  author = '邢慧鹏'
  description = '我的个人资料库'
  hiddenPostSummaryInHomePage = true
  showToc = true
